### ISSUE TITLE
align

### ISSUE THREAD

**Issue by preda-bogdan** [LauraCarmen/Discover-New-Places-#1]
to: @LauraCarmen 

`./scss/main.scss`

[L43](https://github.com/LauraCarmen/Discover-New-Places-/blob/d7e1f827d6f14264fd53c3ab2dd710ef50cf6ce4/scss/main.scss#L43) Cred ca aici e problema, daca folosesti `float` nu mai poti sa aliniezi automat elementul. incearca sa comentezi regula asta eg. `/* float: left; */`

**Comment by preda-bogdan** [comment]
to: @LauraCarmen
[L38](https://github.com/LauraCarmen/Discover-New-Places-/blob/d7e1f827d6f14264fd53c3ab2dd710ef50cf6ce4/scss/main.scss#L38)
```
    text-align: center;               <--- Added this HERE
    align-items: center;
    margin-top: 2rem;
    .three-col-grid {
        display:inline-block        <--- And replaced float with display
        width:percentage(3/12);
        text-align: center;
    }
```

**Comment by LauraCarmen** [comment]
Thank you @preda-bogdan 👍

**Comment by preda-bogdan** [comment]
@LauraCarmen you can close this issue now since it is solved.
